<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Invoice {{ $invoice->invoice_number }}</title>
    <style>
        body { font-family: Arial, sans-serif; font-size: 13px; color: #333; }
        .header { display: flex; justify-content: space-between; margin-bottom: 20px; }
        h1 { color: #1A4FA8; }
        table { width: 100%; border-collapse: collapse; margin-top: 20px; }
        th { background: #1A4FA8; color: #fff; padding: 8px; text-align: left; }
        td { padding: 8px; border-bottom: 1px solid #ddd; }
        .text-right { text-align: right; }
        .total-row td { font-weight: bold; border-top: 2px solid #333; }
        .badge-paid { color: #155724; font-weight: bold; }
        .badge-unpaid { color: #721c24; font-weight: bold; }
        .footer { margin-top: 40px; font-size: 11px; color: #999; text-align: center; }
    </style>
</head>
<body>
    <div class="header">
        <div>
            <h1>LIPAKODI RMS</h1>
            <p>Rental Management System<br>support@lipakodi.co.ke</p>
        </div>
        <div style="text-align:right;">
            <h2>INVOICE</h2>
            <p><strong>{{ $invoice->invoice_number }}</strong><br>
            Date: {{ \Carbon\Carbon::parse($invoice->created_at)->format('d M Y') }}<br>
            Due: {{ \Carbon\Carbon::parse($invoice->due_date)->format('d M Y') }}</p>
        </div>
    </div>

    <hr>

    <div style="display:flex;justify-content:space-between;">
        <div>
            <strong>Bill To:</strong><br>
            {{ $invoice->org_name }}<br>
            {{ $invoice->org_slug }}.lipakodi.co.ke<br>
            {{ $invoice->org_phone }}<br>
            {{ $invoice->org_email }}
        </div>
        <div style="text-align:right;">
            <strong>Status:</strong><br>
            @if($invoice->status === 'paid')
                <span class="badge-paid">PAID</span>
            @else
                <span class="badge-unpaid">UNPAID</span>
            @endif<br>
            <strong>Type:</strong><br>
            {{ $invoice->type === 'sms_credits' ? 'SMS Credits' : 'Subscription' }}
        </div>
    </div>

    <table>
        <thead>
            <tr>
                <th>Description</th>
                <th class="text-right">Amount (KES)</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>{{ $invoice->description ?? ($invoice->type === 'sms_credits' ? 'SMS Credits Purchase' : 'Subscription Fee') }}</td>
                <td class="text-right">{{ number_format($invoice->amount) }}</td>
            </tr>
            <tr class="total-row">
                <td class="text-right">Total Payable</td>
                <td class="text-right">KES {{ number_format($invoice->amount) }}</td>
            </tr>
            @if($invoice->status === 'paid')
            <tr class="total-row">
                <td class="text-right">Amount Paid</td>
                <td class="text-right" style="color:#155724;">KES {{ number_format($invoice->amount) }}</td>
            </tr>
            <tr class="total-row">
                <td class="text-right">Balance Due</td>
                <td class="text-right" style="color:#155724;">KES 0</td>
            </tr>
            @else
            <tr class="total-row">
                <td class="text-right">Balance Due</td>
                <td class="text-right" style="color:#721c24;">KES {{ number_format($invoice->amount) }}</td>
            </tr>
            @endif
        </tbody>
    </table>

    @if($invoice->status === 'paid')
    <p style="margin-top:20px;color:#155724;">
        <strong>Payment Received</strong> via {{ ucfirst($invoice->payment_method ?? 'N/A') }}
        — Ref: {{ $invoice->payment_reference ?? 'N/A' }}
        on {{ $invoice->paid_at ? \Carbon\Carbon::parse($invoice->paid_at)->format('d M Y') : 'N/A' }}
    </p>
    @else
    <p style="margin-top:20px;">
        <strong>Pay via M-Pesa Paybill:</strong><br>
        Business No: {{ config('services.mpesa.shortcode', 'N/A') }}<br>
        Account No: {{ $invoice->invoice_number }}<br>
        Amount: KES {{ number_format($invoice->amount) }}
    </p>
    @endif

    <div class="footer">
        Generated by Lipakodi RMS &mdash; {{ now()->format('d M Y H:i') }}
    </div>
</body>
</html>
