<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Invoice {{ $invoice->invoice_number }}</title>
    <link href="{{ asset('assets/plugins/bootstrap/css/bootstrap.css') }}" rel="stylesheet">
    <style>
        body { background: #fff; }
        @media print {
            .no-print { display: none !important; }
            body { margin: 0; }
        }
    </style>
</head>
<body onload="window.print()">
    <div class="container mt-4">
        <div class="row mb-4">
            <div class="col-6">
                <h3 class="text-primary font-weight-bold">LIPAKODI RMS</h3>
                <p class="text-muted">Rental Management System</p>
            </div>
            <div class="col-6 text-right">
                <h4>INVOICE</h4>
                <p><strong>{{ $invoice->invoice_number }}</strong><br>
                Date: {{ \Carbon\Carbon::parse($invoice->created_at)->format('d M Y') }}<br>
                Due: {{ \Carbon\Carbon::parse($invoice->due_date)->format('d M Y') }}</p>
            </div>
        </div>

        <hr>

        <div class="row mb-4">
            <div class="col-6">
                <strong>Bill To:</strong><br>
                {{ $invoice->org_name }}<br>
                {{ $invoice->org_slug }}.lipakodi.co.ke<br>
                {{ $invoice->org_phone }}<br>
                {{ $invoice->org_email }}
            </div>
            <div class="col-6 text-right">
                <strong>Status:</strong>
                @if($invoice->status === 'paid')
                    <span class="text-success font-weight-bold">PAID</span>
                @else
                    <span class="text-danger font-weight-bold">UNPAID</span>
                @endif<br>
                <strong>Type:</strong>
                {{ $invoice->type === 'sms_credits' ? 'SMS Credits' : 'Subscription' }}
            </div>
        </div>

        <table class="table table-bordered">
            <thead class="bg-primary text-white">
                <tr>
                    <th>Description</th>
                    <th class="text-right">Amount (KES)</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>{{ $invoice->description ?? ($invoice->type === 'sms_credits' ? 'SMS Credits Purchase' : 'Subscription Fee') }}</td>
                    <td class="text-right">{{ number_format($invoice->amount) }}</td>
                </tr>
                <tr>
                    <td class="text-right font-weight-bold">Total Payable</td>
                    <td class="text-right font-weight-bold">KES {{ number_format($invoice->amount) }}</td>
                </tr>
                @if($invoice->status === 'paid')
                <tr>
                    <td class="text-right font-weight-bold">Balance Due</td>
                    <td class="text-right font-weight-bold text-success">KES 0</td>
                </tr>
                @else
                <tr>
                    <td class="text-right font-weight-bold">Balance Due</td>
                    <td class="text-right font-weight-bold text-danger">KES {{ number_format($invoice->amount) }}</td>
                </tr>
                @endif
            </tbody>
        </table>

        <div class="no-print mt-3">
            <button onclick="window.print()" class="btn btn-primary">Print</button>
            <a href="{{ route('super.invoices.show', $invoice->id) }}" class="btn btn-secondary ml-2">Back</a>
        </div>

        <p class="text-muted mt-4 small text-center">Generated by Lipakodi RMS — {{ now()->format('d M Y H:i') }}</p>
    </div>
</body>
</html>
